"""Utilities for saving reproducible model-training artifacts."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf


def save_training_artifacts(
    history: tf.keras.callbacks.History,
    output_dir: str | Path,
) -> dict[str, Path]:
    """
    Save training history and learning curves as reproducible artifacts.

    The persisted CSV is treated as the numerical source of truth.
    Learning curves are generated by reading the saved CSV rather than
    directly from the in-memory Keras History object.

    Args:
        history:
            Keras training history returned by ``model.fit()``.

        output_dir:
            Directory in which the training artifacts are saved.

    Returns:
        Dictionary containing paths to the saved CSV and PNG artifacts.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    history_df = pd.DataFrame(
        history.history
    )

    history_df.index = history_df.index + 1
    history_df.index.name = "epoch"

    history_path = (
        output_dir / "training_history.csv"
    )

    history_df.to_csv(history_path)

    # Reading the persisted history makes the CSV the reproducible
    # numerical source for all learning-curve plots.
    history_df = pd.read_csv(
        history_path,
        index_col="epoch",
    )

    plot_paths: dict[str, Path] = {}

    # Plotting training and validation loss.
    loss_path = (
        output_dir / "learning_curve_loss.png"
    )

    plt.figure()
    plt.plot(
        history_df.index,
        history_df["loss"],
        label="Training loss",
    )
    plt.plot(
        history_df.index,
        history_df["val_loss"],
        label="Validation loss",
    )
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title("LSTM Learning Curve — Loss")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        loss_path,
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()

    plot_paths["loss"] = loss_path

    # Plotting training and validation accuracy.
    accuracy_path = (
        output_dir / "learning_curve_accuracy.png"
    )

    plt.figure()
    plt.plot(
        history_df.index,
        history_df["accuracy"],
        label="Training accuracy",
    )
    plt.plot(
        history_df.index,
        history_df["val_accuracy"],
        label="Validation accuracy",
    )
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title("LSTM Learning Curve — Accuracy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        accuracy_path,
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()

    plot_paths["accuracy"] = accuracy_path

    # Plotting training and validation macro-F1.
    macro_f1_path = (
        output_dir / "learning_curve_macro_f1.png"
    )

    plt.figure()
    plt.plot(
        history_df.index,
        history_df["macro_f1"],
        label="Training macro-F1",
    )
    plt.plot(
        history_df.index,
        history_df["val_macro_f1"],
        label="Validation macro-F1",
    )
    plt.xlabel("Epoch")
    plt.ylabel("Macro-F1")
    plt.title("LSTM Learning Curve — Macro-F1")
    plt.legend()
    plt.tight_layout()
    plt.savefig(
        macro_f1_path,
        dpi=150,
        bbox_inches="tight",
    )
    plt.close()

    plot_paths["macro_f1"] = macro_f1_path

    return {
        "history": history_path,
        **plot_paths,
    }